# fly.toml app configuration file generated for chatgpt-next on 2023-11-29T13:53:08+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "chatgpt-next"
primary_region = "jnb"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "performance"
  cpus = 1
  memory_mb = 2048
